main_page = "https://stellarburgers.nomoreparties.site/"
login_page = f"{main_page}login"
registration_page = f"{main_page}register"
forgot_password_page = f"{main_page}forgot-password"
account_profile_page = f"{main_page}account/profile"